import fs from 'fs';

const reviews = [
  { rating:10, name:'Doğrulanmış misafir', party:'family', date:'2025-09-08', period:'Eylül 2025 · 2 gece', body:'Çok yardımcı oldular. Odalar çok temizdi ve merkeze çok yakındı. Odaları da çok beğendik. Balkonda oturmak çok keyifliydi.', liked:'temizlik, personel ve servis, oda konforu, konum', order:10 },
  { rating:10, name:'Yesim', party:'family', date:'2025-09-05', period:'Ağustos 2025 · 3 gece', body:'Ailenizle vakit geçirebileceğiniz konforlu ve temiz bir mekan. Feribota ve merkeze çok yakın.', liked:'temizlik, personel ve servis, oda konforu', order:20 },
  { rating:10, name:'Fatih', party:'family', date:'2025-07-18', period:'Temmuz 2025 · 3 gece', body:'Oda güzel ve temizdi, otelde kalan diğer insanlar da sıcakkanlıydı. Merkezde olduğu için konumu da çok iyiydi. Bir daha gelsem tekrar bu otelde kalırdım.', liked:'temizlik, oda konforu, konum', reply:'Teşekkürler 😊🙏🏻', reply_date:'2025-07-22', order:30 },
  { rating:10, name:'Hasan', party:'couple', date:'2024-08-28', period:'Ağustos 2024 · 3 gece', title:'Memnun kaldık', body:'Otel seçerken özellikle balkonlu oda olmasına dikkat ettik. Paradise İmroz ise sadece balkonuyla değil, odanın büyüklüğü ve ferahlığıyla bizi oldukça tatmin etti. Merkeze yürüyerek 3-4 dakikalık mesafede, otoparkın olması da bizi memnun etti. Mesut Bey\'den ada hakkında bilgi almanız oldukça faydalı olacaktır.', liked:'temizlik, personel ve servis, oda konforu', reply:'Teşekkürler', reply_date:'2025-08-05', order:40 },
  { rating:10, name:'Doğrulanmış misafir', party:'couple', date:'2024-07-15', period:'Temmuz 2024 · 3 gece', title:'Temiz ve huzurlu bir konaklama', body:'Otel temiz ve yeniydi. Oda, oturma alanı ve balkon güzel ve ferahtı. Banyo biraz küçük ama kullanışlı. Genel olarak sevdik, herhangi bir sorun yaşamadık.', liked:'temizlik, oda konforu', reply:'Teşekkürler', reply_date:'2024-07-13', order:50 },
  { rating:10, name:'Yeliz', party:'family', date:'2024-07-13', period:'Temmuz 2024 · 2 gece', body:'Gökçeada\'ya ilk gelişimizdi. İşletme sahibi Mesut Bey\'e güleryüzlü karşılaması ve ada ile ilgili bilgilendirmeleri için çok teşekkür ederiz. Otel ulaşım açısından çok rahat ve temizdi. 4 kişilik bir aileyiz, odada çok rahat kalabildik.', liked:'temizlik, personel ve servis, oda konforu', reply:'Teşekkürler', reply_date:'2024-06-24', order:60 },
  { rating:10, name:'Tülin', party:null, date:'2024-07-13', period:'Temmuz 2024 · 2 gece', body:'Merkezde, temiz, çok ferah odaları olan bir yer. Evimizde gibi hissettik. Memnun kaldık, teşekkürler.', liked:'temizlik, oda konforu', reply:'Teşekkürler', reply_date:'2024-07-13', order:70 },
  { rating:10, name:'Serdar', party:'family', date:'2024-06-24', period:'Haziran 2024 · 5 gece', title:'Temiz yeni bir otel', body:'Otel yeni ve odaları gayet büyük, yeterli. Tertemiz, her yere çok yakın.', liked:'temizlik, personel ve servis, oda konforu, konum', reply:'Teşekkürler', reply_date:'2024-06-24', order:80 },
  { rating:10, name:'Almila Nur', party:'couple', date:'2024-04-25', period:'Nisan 2024 · 2 gece', body:'İşletme sahibi çok cana yakın ve ilgiliydi. Adanın tarihi ve kültürel yapısı hakkında bizi bilgilendirdi ve bu çok hoşumuza gitti. Gayet temiz ve lokasyonu güzel bir konaklama deneyimi yaşadık.', liked:'temizlik, personel ve servis, oda konforu', reply:'Memnun kalmanız ve keyif almanız bizim için çok değerli', reply_date:'2024-04-25', order:90 },
  { rating:10, name:'Ahmet', party:'family', date:'2024-04-14', period:'Nisan 2024 · 2 gece', title:'Temiz otel', body:'Gerçekten güzel bir deneyimdi. Ailecek rahat kaldık, gayet güzel temiz ve rahat bir tatil oldu. Sadece oda isteyenler için merkeze yakın, nezih güzel bir otel — tavsiye ederim.', liked:'temizlik, personel ve servis, oda konforu', reply:'Sizleri tekrar misafir etmekten mutluluk duyarız.', reply_date:'2024-04-14', order:100 },
  { rating:10, name:'Ece Naz', party:null, date:'2023-08-12', period:'Ağustos 2023 · 3 gece', title:'Harika', body:'Otel yeni açılmış, her şey temiz ve özenli. Önde minik bir balkon var, oradaki şezlonglar da çok rahattı. Genel olarak Özgür Bey de çok yardımcı oldu, birçok tavsiyede bulundu. Her şey için teşekkürler.', liked:'temizlik, personel ve servis, oda konforu', reply:'Sizleri misafir etmekten mutluluk duyduk.', reply_date:'2023-08-17', order:110 },
  { rating:8, name:'Ayhan', party:'family', date:'2026-05-18', period:'Mayıs 2026 · 2 gece', body:'Otopark sorunu yok, merkezi bir yerde ve oda temizdi. Camiye yakın olmasından dolayı ses tamamen içeride; ses yalıtım sorunu var. Sahipleri çok yardımsever ve ada hakkında detaylı bilgi verdiler.', liked:'temizlik, personel ve servis, konum', order:120 },
  { rating:8, name:'Erhan', party:'family', date:'2025-08-02', period:'Temmuz 2025 · 4 gece', title:'Aile Seyahati', body:'Ailecek Gökçeada seyahatimizde dört gece konakladığımız mekan. Mesut Bey başta olmak üzere personel güler yüzlü ve yardımcıydı. Temiz, güvenli ve konforluydu. Konum, merkeze yürüyüş mesafesinde. Yolumuz yeniden Gökçeada\'ya düşerse tercihimizi buradan yana kullanırız.', liked:'temizlik, personel ve servis, oda konforu', reply:'Teşekkürler', reply_date:'2025-08-05', order:130 },
  { rating:8, name:'gülsüm', party:'family', date:'2024-07-19', period:'Temmuz 2024 · 3 gece', body:'Konumunun merkeze yakın olması çok güzel. Odaları 4 kişilik bir aile için biraz küçük ama kısa konaklamamızda çok sorun yaratmadı. Gayet temiz ve şirin bir otel. Mesut Bey sorularımızı kibarlıkla yanıtladı.', liked:'temizlik, personel ve servis, oda konforu', reply:'Teşekkürler', reply_date:'2025-08-05', order:140 },
];

function q(s) { return s == null ? 'null' : "'" + String(s).replace(/'/g, "''") + "'"; }

const sql = "insert into public.reviews (rating, guest_name, traveled_with, posted_date, stay_period, body_title, body, liked, hotel_reply, reply_date, sort_order, visible) values\n" +
  reviews.map(r => `(${r.rating}, ${q(r.name)}, ${q(r.party)}, ${q(r.date)}, ${q(r.period)}, ${q(r.title)}, ${q(r.body)}, ${q(r.liked)}, ${q(r.reply)}, ${q(r.reply_date)}, ${r.order}, true)`).join(',\n') +
  ' on conflict do nothing;';

fs.writeFileSync(new URL('../.tmp-sql.json', import.meta.url), JSON.stringify({ query: sql }));
console.log('rows:', reviews.length, '· length:', sql.length);
